### PR TITLE
Fixing v2 signature not merging headers_to_sign with resource

### PR DESCRIPTION
**Pull request by gullitmiranda**
The google storage v2 signature pattern: https://cloud.google.com/storage/docs/access-control/signed-urls-v2#string-components

### CODE REVIEW

**Comment by mcrumm** [comment]
Hi @gullitmiranda - I'm not sure what this change is providing. At a glance, it looks like the output would be the same as the current implementation.

Can you explain what's driving this change?  Are there any additional tests we could add to make it clearer what's wrong with the current implementation?  Thanks!

**Comment by gullitmiranda** [comment]
hi @mcrumm, sorry, after a refactor i have lost de core of the fix :/
now i rollback de fix and added some tests

But for you to know, the problem is that we should only add `\n` when the `headers_to_sign` is not empty.

compare outputs: 
```diff
# without extensions
- "PUT\n\n\n1582478988\n\n/foo/bar.txt"
+ "PUT\n\n\n1582478988\n/foo/bar.txt"

# with extensions
"PUT\n\nimage/jpeg\n1582479575\nx-goog-acl:public-read\nx-goog-meta-environment:test\n/foo/bar.txt"
```

**Review by mcrumm — COMMENTED** [review]
@gullitmiranda okay, that makes sense :)

I dropped a couple _tiny_ comments, but overall this looks great! ❤️

**Comment by gullitmiranda** [comment]
all done @mcrumm

**Review by mcrumm — APPROVED** [review]
❤️❤️❤️

**Pull request merged**
